### PR TITLE
Set default control dir to be created under `/tmp`

### LINKED ISSUE #27: Connection failure depending on the current working directory
I have a code that calls `Session::connect(...).await`. It runs fine most of the time, but fails with "failed to connect to the remote host", when run from inside a certain directory (or its children). (I.e., the only thing that changes is the current working directory.) I don't see anything special about that directory, but perhaps I'm missing something. Any pointers on what this could be, or how to go about debugging it?

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #27 

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by NobodyXu** [comment]
> I'm hesitant to do this, because it means that the control file is going to end up in a potentially globally-readable location, which might give other users on the same machine access to the connection.

I just checked the control socket created, it is created with `rw-------` so that no other user can access it.
We can also change the permission of the temporary directory we created.

> I would prefer if we instead defaulted to somewhere under `~`. Judging by the XDG Base Directory spec,

I don't think storing it in `$HOME` is a good idea.
If the program/machine terminated without cleanup, then these temporary directory would be in `$HOME` forever.

I would rather like to use `/run/user/$UID`, which resides in a tmpfs while being only accessible to the current user.



Speaking of which, I realize there is a fundamental problem with `openssh-rs`.
If the user change the uid after ssh multiplex master is spawned, then we won't be able to access that control socket.

We should probably add a warning.

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/openssh-rs/28)

**Comment by jonhoo** [comment]
Ah, sorry, I meant `$XDG_RUNTIME_DIR`, not `$XDG_STATE_HOME`. `$XDG_RUNTIME_DIR` is set to `/run/user/UID`, so we're in agreement. But we should respect the environment variable regardless for those cases where the user specifically wants to use a different location.

As for users changing UID, that I don't think is a big problem, as it should be a fairly rare occurrence.

**Comment by NobodyXu** [comment]
Cool.

I would update this PR, though I would prefer #26 to be merged first.

**Comment by jonhoo** [comment]
That seems reasonable. Sorry, I haven't gotten back to #26 yet — life keeps demanding time :) I promise you it's on my radar!

**Comment by NobodyXu** [comment]
@jonhoo I've rebased this PR against #26 and set default control dir to `$XDG_STATE_HOME` or `$HOME/.local/state` if the former is not set, or `/tmp` if both environment variable is not set.

**Comment by NobodyXu** [comment]
@jonhoo Some integrated failed due to the fact that `$HOME/.local/state` does not exist.

Shall we use `fs::create_dir_all` to create the directory, or fallback to `"/tmp"`?

**Comment by jonhoo** [comment]
Let's go with `create_dir_all`. `/tmp` seems too risky to me.

**Comment by NobodyXu** [comment]
> Let's go with `create_dir_all`. `/tmp` seems too risky to me.

I forgot to ask, what if `create_dir_all` also failed?

Shall we then fallback to `/tmp`, which is the only reasonable behavior I can think of?

**Comment by jonhoo** [comment]
If the `create_dir_all` fails, I think we should return an error.

**Comment by NobodyXu** [comment]
@jonhoo This PR currently finds home directory via looking up environment variable `$HOME`, which IMO is a bit fragile.

Shall we add something like [`dirs::state_dir`](https://docs.rs/dirs/latest/dirs/fn.state_dir.html) to the dependency?

It fallbacks to using `libc::getpwuid_r` to obtain home dir when `$HOME` is not set.

**Comment by jonhoo** [comment]
Yes, that sounds like a good idea!

**Comment by NobodyXu** [comment]
@jonhoo I now uses `dirs::home_dir` and I think this PR is ready to merge!

Can you please review this PR?

File: src/builder.rs [hunk 1]
```diff
@@ -7,14 +7,45 @@ use super::process_impl;
...
 use tempfile::{Builder, TempDir};
 use tokio::process;
 
+/// The returned `&'static Path` can be coreced to any lifetime.
+fn get_default_control_dir<'a>() -> Result<&'a Path, Error> {
+    static DEFAULT_CONTROL_DIR: OnceCell<Option<Box<Path>>> = OnceCell::new();
+
+    DEFAULT_CONTROL_DIR
+        .get_or_try_init(|| {
+            if let Some(xdg_state_home) = env::var_os("XDG_STATE_HOME") {
```
Comment (jonhoo) [inline src/builder.rs:27]: Why use this instead of [`dirs::state_dir`](https://docs.rs/dirs/latest/dirs/fn.state_dir.html)?

Comment (NobodyXu) [reply src/builder.rs:27]: Well, I used that so that `fs::create_dir_all` is only called for `$HOME/.local/state`.

I don't know whether it is a good idea to `fs::create_all($XDG_STATE_HOME)`.

Comment (jonhoo) [reply src/builder.rs:27]: I don't think that should be a problem. The current process already runs as the user, so should be fine.

Comment (NobodyXu) [reply src/builder.rs]: OK, I have updated the `get_default_control_dir` to use `dirs::state_dir`.

File: src/builder.rs [hunk 2]
```diff
@@ -12,9 +12,32 @@ use std::path::{Path, PathBuf};
...
+
+                Ok(Some(state_dir.into_boxed_path()))
+            } else {
+                Ok(None)
+            }
+        })
+        .map(|default_control_dir| {
+            default_control_dir
+                .as_deref()
+                .unwrap_or_else(|| Path::new("/tmp"))
```
Comment (jonhoo) [inline src/builder.rs:37]: I think we should _never_ fall back to `/tmp`. _That_ is a security problem waiting to happen. It should either fall back to something like `./`, or we should return an error.

Comment (NobodyXu) [reply src/builder.rs]: I have set the fallback path to `./`.

Since we uses `./` for control directory before this PR, I believe we should also use it as a fallback.

**Review by jonhoo — APPROVED** [review]

**Comment by NobodyXu** [comment]
@jonhoo I think we can now do a major release so that users can test out the new native-mux impelemtation.

**Comment by jonhoo** [comment]
Published as 0.9.0-rc.1 :tada:

**Comment by NobodyXu** [comment]
Cheers!

**Comment by NobodyXu** [comment]
> Published as 0.9.0-rc.1 tada

I have tried 0.9.0-rc.1 in my own binary crate [ssh-utils](https://github.com/NobodyXu/ssh-utils) and so far I haven't encountered any bug.
